name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "pomomural"
          heroku_email: "ethanho@uchicago.edu"
          usedocker: true
        env:
          HD_ORS_KEY: ${{secrets.ORS_KEY}}
